// These types only provide for annotations, and not guarantee the type safety.
// I'm working on storing the dimensions in the types, but most of TSL functions
// are not generic and don't preserve the types anyways.

export type Length = 'float'
export type Wavelength = 'float'
export type Angle = 'float'
export type SolidAngle = 'float'
export type Power = 'float'
export type LuminousPower = 'float'

export type Dimensionless = 'float'
export type InverseLength = 'float'
export type Area = 'float'
export type Volume = 'float'
export type NumberDensity = 'float'
export type Irradiance = 'float'
export type Radiance = 'float'
export type SpectralPower = 'float'
export type SpectralIrradiance = 'float'
export type SpectralRadiance = 'float'
export type SpectralRadianceDensity = 'float'
export type ScatteringCoefficient = 'float'
export type InverseSolidAngle = 'float'
export type LuminousIntensity = 'float'
export type Luminance = 'float'
export type Illuminance = 'float'

export type AbstractSpectrum = 'vec3'
export type DimensionlessSpectrum = 'vec3'
export type PowerSpectrum = 'vec3'
export type IrradianceSpectrum = 'vec3'
export type RadianceSpectrum = 'vec3'
export type RadianceDensitySpectrum = 'vec3'
export type ScatteringSpectrum = 'vec3'

export type Position = 'vec3'
export type Direction = 'vec3'
export type Luminance3 = 'vec3'
export type Illuminance3 = 'vec3'

export type TransmittanceTexture = 'texture'
export type AbstractScatteringTexture = 'texture3D'
export type ReducedScatteringTexture = 'texture3D'
export type ScatteringTexture = 'texture3D'
export type ScatteringDensityTexture = 'texture3D'
export type IrradianceTexture = 'texture'

export const Length = 'float'
export const Wavelength = 'float'
export const Angle = 'float'
export const SolidAngle = 'float'
export const Power = 'float'
export const LuminousPower = 'float'

export const Dimensionless = 'float'
export const InverseLength = 'float'
export const Area = 'float'
export const Volume = 'float'
export const NumberDensity = 'float'
export const Irradiance = 'float'
export const Radiance = 'float'
export const SpectralPower = 'float'
export const SpectralIrradiance = 'float'
export const SpectralRadiance = 'float'
export const SpectralRadianceDensity = 'float'
export const ScatteringCoefficient = 'float'
export const InverseSolidAngle = 'float'
export const LuminousIntensity = 'float'
export const Luminance = 'float'
export const Illuminance = 'float'

export const AbstractSpectrum = 'vec3'
export const DimensionlessSpectrum = 'vec3'
export const PowerSpectrum = 'vec3'
export const IrradianceSpectrum = 'vec3'
export const RadianceSpectrum = 'vec3'
export const RadianceDensitySpectrum = 'vec3'
export const ScatteringSpectrum = 'vec3'

export const Position = 'vec3'
export const Direction = 'vec3'
export const Luminance3 = 'vec3'
export const Illuminance3 = 'vec3'

export const TransmittanceTexture = 'texture'
export const AbstractScatteringTexture = 'texture3D'
export const ReducedScatteringTexture = 'texture3D'
export const ScatteringTexture = 'texture3D'
export const ScatteringDensityTexture = 'texture3D'
export const IrradianceTexture = 'texture'
