export const IRRADIANCE_TEXTURE_WIDTH = 64
export const IRRADIANCE_TEXTURE_HEIGHT = 16
export const SCATTERING_TEXTURE_WIDTH = 256
export const SCATTERING_TEXTURE_HEIGHT = 128
export const SCATTERING_TEXTURE_DEPTH = 32
export const TRANSMITTANCE_TEXTURE_WIDTH = 256
export const TRANSMITTANCE_TEXTURE_HEIGHT = 64
export const METER_TO_LENGTH_UNIT = 1 / 1000
